# Default values for argo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

apps:
- name: keycloak
  project: "default"
  source:
    repoURL: "https://codecentric.github.io/helm-charts"
    chart: keycloak
    targetRevision: 6.2.0
    helm:
      valueFiles:
        - values.yaml
      # values: |-
      #   key: value
      parameters:
        keycloak.serviceAccount.create: true
  destinations:
  - server: "https://kubernetes.default.svc"
    namesapce: keycloak
    name: "1"
    source:
      helm:
        valueFiles:
          - values-env.yaml
        parameters:
          keycloak.ingress.enabled: true
  - server: "https://kubernetes.default.svc"
    namesapce: keycloak2
    name: "2"
    source:
      helm:
        parameters:
          postgresql.persistence.enabled: true