{{/*
# https://helm.sh/docs/chart_template_guide/functions_and_pipelines/
# https://github.com/Masterminds/sprig/blob/master/docs/dicts.md#merge-mustmerge
*/}}
{{- $root := . }}
{{- range $app := .Values.apps }}
{{- range $index, $dest := $app.destinations }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ ($dest.name | default $index) | printf "%s-%s-%s" $root.Release.Name $app.name }}
  labels:
    app: {{ template "argo-app.name" $root }}
    chart: {{ template "argo-app.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  project: {{ $app.project | default "default" }}
  source:
{{- $merged := merge dict $app.source $dest.source }}
{{ toYaml $merged | indent 4 }}
  destination:
    server: {{ $dest.server }}
    namesapce: {{ $dest.namesapce }}
---
{{- end }}
{{- end }}