{{/*
# https://helm.sh/docs/chart_template_guide/functions_and_pipelines/
# https://github.com/Masterminds/sprig/blob/master/docs/dicts.md#merge-mustmerge
*/}}
{{- $root := . }}
{{- $tpl  := .Values.template }}
{{- range $index, $app := .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name | default ($index | toString) | printf "%s-%s" $root.Release.Name  }}
  labels:
    chart: {{ template "argo-app.chart" $root }}
    release: {{ $root.Release.Name }}
{{- $merged := index $tpl $app.template }}
{{- $merged := merge dict (omit $app "name" "template") $merged }}
spec:
{{ toYaml $merged | indent 2 }}
---
{{- end }}